"""Parity gate: committed pocket JSON must equal a fresh export.

The pocket web detector reads ``pocket-app/src/vision/{dictionary,geometry}.json``,
which are generated by ``tools/export_dictionary.py`` from the exact same
``cv2.aruco`` bit matrices and ``assets.toml`` geometry that drive print and
Python detection. If print/detection ever change, these committed JSON files
must be regenerated — this test fails loudly until they are, so the browser
detector can never silently drift from the physical tiles.

Regenerate with::

    uv run python tools/export_dictionary.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "tools") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "tools"))

import export_dictionary as exp  # noqa: E402


def _committed(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_dictionary_json_matches_fresh_export() -> None:
    assert exp.DICTIONARY_PATH.is_file(), (
        "pocket dictionary.json missing — run tools/export_dictionary.py"
    )
    assert _committed(exp.DICTIONARY_PATH) == exp.build_dictionary()


def test_geometry_json_matches_fresh_export() -> None:
    assert exp.GEOMETRY_PATH.is_file(), (
        "pocket geometry.json missing — run tools/export_dictionary.py"
    )
    assert _committed(exp.GEOMETRY_PATH) == exp.build_geometry()


def test_dictionary_covers_every_detectable_id() -> None:
    from qamposer_vision.markers import (
        DETECTABLE_IDS,
        MARKER_TABLE,
        MEASURE_BLOCK_ID,
        QUBIT_WIRE_ID,
    )

    exported = exp.build_dictionary()["markers"]
    assert {int(k) for k in exported} == set(DETECTABLE_IDS)
    # 30 IDs: the 28 gate/corner table entries (4 corners + 4 single-qubit +
    # 2 CNOT halves + 12 rotations + S/T + 3 RX/RY/RZ dials + 1 SWAP ×) plus the
    # two furniture blocks — the qubit-wire block (#95) and the measurement
    # block (#97) — which the browser must decode but which are NOT gates.
    assert len(exported) == 30
    assert len(MARKER_TABLE) == 28
    assert {QUBIT_WIRE_ID, MEASURE_BLOCK_ID} <= set(DETECTABLE_IDS)
    assert QUBIT_WIRE_ID not in MARKER_TABLE
    assert MEASURE_BLOCK_ID not in MARKER_TABLE
    # The IDs freed by task #96 must not have leaked back into the export.
    assert not ({11, 14} & {int(k) for k in exported})


def test_every_marker_has_four_distinct_rotations_all_ids_unique() -> None:
    exported = exp.build_dictionary()["markers"]
    seen: dict[int, str] = {}
    for mid, entry in exported.items():
        rotations = entry["rotations"]
        assert len(rotations) == 4
        assert len(entry["bits"]) == 4 and all(len(r) == 4 for r in entry["bits"])
        # No two *different* markers may share any rotation code (Hamming-safe).
        for code in rotations:
            prior = seen.get(code)
            assert prior is None or prior == mid, (
                f"marker {mid} rotation code {code} collides with marker {prior}"
            )
            seen[code] = mid
