/**
 * Every URL the Guide's prose links to — shared by all languages, so a
 * translation can never point somewhere else.
 */
import kitPdf from '../../../../examples/print/entangible-print-kit-A4.pdf?url';
import cubeFamily from '../../../../examples/renders/cube-family.png';

export const REPO_URL = 'https://github.com/JanLahmann/entangible';
export const ISSUES_URL = 'https://github.com/JanLahmann/entangible/issues';

/**
 * Kit downloads that are BUILT, not committed (#88).
 *
 * The 3D and laser kits and the full-size board PDF are regenerated by
 * `.github/workflows/artifacts.yml` and published as release assets, so
 * `releases/latest/download/<asset>` always serves the current kit. Bundling them instead would put ~37 MB of zip into
 * every visitor's site build and freeze it at whatever the last commit held —
 * which is exactly how the checked-in copy went stale.
 *
 * These are cross-origin, so `download` would be ignored: they are plain links
 * that open in a new tab, and GitHub serves them as attachments anyway.
 */
const RELEASE_BASE = 'https://github.com/JanLahmann/entangible/releases/latest/download';
export const TILES_3D_URL = `${RELEASE_BASE}/entangible-3d-tiles.zip`;
export const LASER_KIT_URL = `${RELEASE_BASE}/entangible-laser-kit.zip`;
export const BOARD_PDF_URL = `${RELEASE_BASE}/entangible-board-720x500.pdf`;
export const QAMPOSER_URL = 'https://qamposer.org';
export const FAMILY_URL = 'https://fun-with-quantum.org';
export const COMPOSER_URL = 'https://quantum.cloud.ibm.com/composer';
export const IBM_REGISTRATION_URL = 'https://quantum.cloud.ibm.com/registration';

/** The bundled print kit (hashed into dist) and the gate-cube render. */
export { kitPdf, cubeFamily };
